### ISSUE TITLE
Missing options when using ckeditor type

### ISSUE THREAD

**Issue by roldan** [lexxpavlov/LexxpavlovSettingsBundle#6]
Hi, 

I'm using lexxpavlov/settingsbundle 1.3.1 and egeloen/ckeditor-bundle 5.0.3 and after installing both bundles and tried to create or edit a setting, I get this exception:

![screenshot from 2017-06-25 05-42-23](https://user-images.githubusercontent.com/695904/27514716-1bf984b0-5969-11e7-9e78-d7993e6bcd0b.png)

The same occurs for all this vars: async, jquery, require_js, auto_inline, inline, input_sync, filebrowsers

So I noticed that there are some missing options here:

https://github.com/lexxpavlov/LexxpavlovSettingsBundle/blob/master/Form/Type/SettingValueType.php#L49

That the ckeditor widget needs here:

https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/views/Form/ckeditor_widget.html.twig

Maybe you should add default value for these vars, what do you think about? 

Best,
Matías

**Comment by lexxpavlov** [comment]
Maybe, this variables was created in fifth version of egeloen/ckeditor-bundle. I will try to fix it in a two days.

**Comment by roldan** [comment]
Great Alexey, thanks!

**Comment by lexxpavlov** [comment]
A new 1.3.2 version fixes this issue. CKEditor will use settings of IvoryCKEditorBundle now.
