### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by magedan** [lexxpavlov/LexxpavlovSettingsBundle#9]
Any chance your bundle can support Symfony 4? Maybe, 2.0 branch.

I found this repository https://github.com/vsavritsky/VsavritskySettingsBundle which is literally a copy of your bundle with some deprecations removed/updated.

Great job, btw!

**Comment by lexxpavlov** [comment]
Hi Dan! 
Can you test my bundle from master in Symfony4? User @PierrickMartos already done needed changes, but I don't update repo yet. Simple require newest version by this command:
```bash
$ composer require --dev lexxpavlov/settingsbundle:dev-master
```

**Comment by magedan** [comment]
Here is what I got:
```
$ composer require --dev lexxpavlov/settingsbundle:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for __root__ dev-develop -> satisfiable by __root__[dev-develop].
- lexxpavlov/settingsbundle dev-master requires symfony/symfony >=2.6 -> satisfiable by symfony/symfony[v4.3.0, v4.3.1, v4.3.2].
- symfony/symfony v4.3.0 conflicts with __root__[dev-develop].
- symfony/symfony v4.3.1 conflicts with __root__[dev-develop].
- symfony/symfony v4.3.2 conflicts with __root__[dev-develop].
- Installation request for lexxpavlov/settingsbundle dev-master -> satisfiable by lexxpavlov/settingsbundle[dev-master].
```

`__root__ dev-develop` - because I left "name" empty in composer.json

Symfony 4.3.2, Composer is 1.86, PHP 7.2.19, Ubuntu 19.04 if that makes sense.

**Comment by lexxpavlov** [comment]
Hi Dan!
Can you test a new release 1.5.1?

**Comment by PierrickMartos** [comment]
Works perfectly for us on Symfony `4.4.14`
